### ISSUE TITLE
Bugs in dataflow analysis

### ISSUE THREAD

**Issue by willow-ahrens** [willow-ahrens/Finch.jl#339] opened 2023-12-05 20:31 UTC
@nullplay

**Comment by nullplay** [comment] 2023-12-18 08:31
## Reproducible Test
```
Output = Fiber!(SparseList(Dense(Element(0))))
Point = Fiber!(SparseList((Element(0))))
Kernel = Fiber!(SparseList(Dense((Element(0)))))

@finch_code begin
       Output .= 0
       for x = _
        for xx = _
         for m = _
           Output[m,x] += Point[x] * Kernel[m,xx]
         end
        end
       end
       end
```

## Generated Code (Problem : ```Output``` will be never updated because ```Output_lvldirty``` has been marked as dead.)
```
quote
    Output_lvl = (ex.bodies[1]).tns.bind.lvl
    Output_lvl_ptr = Output_lvl.ptr
    Output_lvl_idx = Output_lvl.idx
    Output_lvl_2 = Output_lvl.lvl
    Output_lvl_3 = Output_lvl_2.lvl
    Output_lvl_2_val = Output_lvl_2.lvl.val
    Point_lvl = ((ex.bodies[2]).body.body.body.rhs.args[1]).tns.bind.lvl
    Point_lvl_ptr = Point_lvl.ptr
    Point_lvl_idx = Point_lvl.idx
    Point_lvl_val = Point_lvl.lvl.val
    Kernel_lvl = ((ex.bodies[2]).body.body.body.rhs.args[2]).tns.bind.lvl
    Kernel_lvl_ptr = Kernel_lvl.ptr
    Kernel_lvl_idx = Kernel_lvl.idx
    Kernel_lvl_2 = Kernel_lvl.lvl
    Kernel_lvl_2_val = Kernel_lvl_2.lvl.val
    Output_lvl_qos_stop = 0
    Finch.resize_if_smaller!(Output_lvl_ptr, 1 + 1)
    Finch.fill_range!(Output_lvl_ptr, 0, 1 + 1, 1 + 1)
    Output_lvl_qos = 0 + 1
    0 < 1 || throw(FinchProtocolError("SparseListLevels cannot be updated multiple times"))
    Point_lvl_q = Point_lvl_ptr[1]
    Point_lvl_q_stop = Point_lvl_ptr[1 + 1]
    if Point_lvl_q < Point_lvl_q_stop
        Point_lvl_i1 = Point_lvl_idx[Point_lvl_q_stop - 1]
    else
        Point_lvl_i1 = 0
    end
    phase_stop = min(Point_lvl_i1, Point_lvl.shape)
    if phase_stop >= 1
        if Point_lvl_idx[Point_lvl_q] < 1
            Point_lvl_q = Finch.scansearch(Point_lvl_idx, 1, Point_lvl_q, Point_lvl_q_stop - 1)
        end
        while true
            Point_lvl_i = Point_lvl_idx[Point_lvl_q]
            if Point_lvl_i < phase_stop
                Point_lvl_2_val = Point_lvl_val[Point_lvl_q]
                if Output_lvl_qos > Output_lvl_qos_stop
                    Output_lvl_qos_stop = max(Output_lvl_qos_stop << 1, 1)
                    Finch.resize_if_smaller!(Output_lvl_idx, Output_lvl_qos_stop)
                    pos_start = 1 + Kernel_lvl_2.shape * (-1 + Output_lvl_qos)
                    pos_stop = Kernel_lvl_2.shape * Output_lvl_qos_stop
                    Finch.resize_if_smaller!(Output_lvl_2_val, pos_stop)
                    Finch.fill_range!(Output_lvl_2_val, 0, pos_start, pos_stop)
                end
                Output_lvldirty = false
                Kernel_lvl_q = Kernel_lvl_ptr[1]
                Kernel_lvl_q_stop = Kernel_lvl_ptr[1 + 1]
                if Kernel_lvl_q < Kernel_lvl_q_stop
                    Kernel_lvl_i1 = Kernel_lvl_idx[Kernel_lvl_q_stop - 1]
                else
                    Kernel_lvl_i1 = 0
                end
                phase_stop_3 = min(Kernel_lvl_i1, Kernel_lvl.shape)
                if phase_stop_3 >= 1
                    if Kernel_lvl_idx[Kernel_lvl_q] < 1
                        Kernel_lvl_q = Finch.scansearch(Kernel_lvl_idx, 1, Kernel_lvl_q, Kernel_lvl_q_stop - 1)
                    end
                    while true
                        Kernel_lvl_i = Kernel_lvl_idx[Kernel_lvl_q]
                        if Kernel_lvl_i < phase_stop_3
                            for m_4 = 1:Kernel_lvl_2.shape
                                Output_lvl_2_q = (Output_lvl_qos - 1) * Kernel_lvl_2.shape + m_4
                                Kernel_lvl_2_q = (Kernel_lvl_q - 1) * Kernel_lvl_2.shape + m_4
                                Kernel_lvl_3_val = Kernel_lvl_2_val[Kernel_lvl_2_q]
                                Output_lvl_2_val[Output_lvl_2_q] = Point_lvl_2_val * Kernel_lvl_3_val + Output_lvl_2_val[Output_lvl_2_q]
                            end
                            Kernel_lvl_q += 1
                        else
                            phase_stop_5 = min(Kernel_lvl_i, phase_stop_3)
                            if Kernel_lvl_i == phase_stop_5
                                for m_5 = 1:Kernel_lvl_2.shape
                                    Output_lvl_2_q = (Output_lvl_qos - 1) * Kernel_lvl_2.shape + m_5
                                    Kernel_lvl_2_q = (Kernel_lvl_q - 1) * Kernel_lvl_2.shape + m_5
                                    Kernel_lvl_3_val_2 = Kernel_lvl_2_val[Kernel_lvl_2_q]
                                    Output_lvl_2_val[Output_lvl_2_q] = Point_lvl_2_val * Kernel_lvl_3_val_2 + Output_lvl_2_val[Output_lvl_2_q]
                                end
                                Kernel_lvl_q += 1
                            end
                            break
                        end
                    end
                end
                if Output_lvldirty
                    Output_lvl_idx[Output_lvl_qos] = Point_lvl_i
                    Output_lvl_qos += 1
                end
                Point_lvl_q += 1
            else
                phase_stop_7 = min(Point_lvl_i, phase_stop)
                if Point_lvl_i == phase_stop_7
                    Point_lvl_2_val = Point_lvl_val[Point_lvl_q]
                    if Output_lvl_qos > Output_lvl_qos_stop
                        Output_lvl_qos_stop = max(Output_lvl_qos_stop << 1, 1)
                        Finch.resize_if_smaller!(Output_lvl_idx, Output_lvl_qos_stop)
                        pos_start_2 = 1 + Kernel_lvl_2.shape * (-1 + Output_lvl_qos)
                        pos_stop_2 = Kernel_lvl_2.shape * Output_lvl_qos_stop
                        Finch.resize_if_smaller!(Output_lvl_2_val, pos_stop_2)
                        Finch.fill_range!(Output_lvl_2_val, 0, pos_start_2, pos_stop_2)
                    end
                    Output_lvldirty = false
                    Kernel_lvl_q = Kernel_lvl_ptr[1]
                    Kernel_lvl_q_stop = Kernel_lvl_ptr[1 + 1]
                    if Kernel_lvl_q < Kernel_lvl_q_stop
                        Kernel_lvl_i1 = Kernel_lvl_idx[Kernel_lvl_q_stop - 1]
                    else
                        Kernel_lvl_i1 = 0
                    end
                    phase_stop_8 = min(Kernel_lvl_i1, Kernel_lvl.shape)
                    if phase_stop_8 >= 1
                        if Kernel_lvl_idx[Kernel_lvl_q] < 1
                            Kernel_lvl_q = Finch.scansearch(Kernel_lvl_idx, 1, Kernel_lvl_q, Kernel_lvl_q_stop - 1)
                        end
                        while true
                            Kernel_lvl_i = Kernel_lvl_idx[Kernel_lvl_q]
                            if Kernel_lvl_i < phase_stop_8
                                for m_6 = 1:Kernel_lvl_2.shape
                                    Output_lvl_2_q_2 = (Output_lvl_qos - 1) * Kernel_lvl_2.shape + m_6
                                    Kernel_lvl_2_q_2 = (Kernel_lvl_q - 1) * Kernel_lvl_2.shape + m_6
                                    Kernel_lvl_3_val_3 = Kernel_lvl_2_val[Kernel_lvl_2_q_2]
                                    Output_lvl_2_val[Output_lvl_2_q_2] = Point_lvl_2_val * Kernel_lvl_3_val_3 + Output_lvl_2_val[Output_lvl_2_q_2]
                                end
                                Kernel_lvl_q += 1
                            else
                                phase_stop_10 = min(Kernel_lvl_i, phase_stop_8)
                                if Kernel_lvl_i == phase_stop_10
                                    for m_7 = 1:Kernel_lvl_2.shape
                                        Output_lvl_2_q_2 = (Output_lvl_qos - 1) * Kernel_lvl_2.shape + m_7
                                        Kernel_lvl_2_q_2 = (Kernel_lvl_q - 1) * Kernel_lvl_2.shape + m_7
                                        Kernel_lvl_3_val_4 = Kernel_lvl_2_val[Kernel_lvl_2_q_2]
                                        Output_lvl_2_val[Output_lvl_2_q_2] = Point_lvl_2_val * Kernel_lvl_3_val_4 + Output_lvl_2_val[Output_lvl_2_q_2]
                                    end
                                    Kernel_lvl_q += 1
                                end
                                break
                            end
                        end
                    end
                    if Output_lvldirty
                        Output_lvl_idx[Output_lvl_qos] = phase_stop_7
                        Output_lvl_qos += 1
                    end
                    Point_lvl_q += 1
                end
                break
            end
        end
    end
    Output_lvl_ptr[1 + 1] = (Output_lvl_qos - 0) - 1
    for p = 2:1 + 1
        Output_lvl_ptr[p] += Output_lvl_ptr[p - 1]
    end
    resize!(Output_lvl_ptr, 1 + 1)
    qos = Output_lvl_ptr[end] - 1
    resize!(Output_lvl_idx, qos)
    qos_2 = qos * Kernel_lvl_2.shape
    resize!(Output_lvl_2_val, qos_2)
    (Output = Fiber((SparseListLevel){Int64}((DenseLevel){Int64}(Output_lvl_3, Kernel_lvl_2.shape), Point_lvl.shape, Output_lvl_ptr, Output_lvl_idx)),)
end
```

**Closed** 2023-12-20 20:36 UTC
